version: '2.4'

services:
  windows-builder:
    image: captainhook-winbuild
    build: .
    container_name: ch_win_builder
    volumes:
      - .:/src
    command: wine python.exe -m PyInstaller --onefile --name CaptainHook --paths=/src/build_staging build_staging/src/client/main.py

  # Build for Linux (.bin) - Native
  linux-builder:
    image: python:3.12-slim
    volumes:
      - .:/src
    working_dir: /src
    command: |
      bash -c "pip install pyinstaller discord.py aiohttp mss psutil pyautogui pynput ping3 rich cryptography==38.0.4 && pyinstaller --onefile --name CaptainHook --paths=/src/build_staging build_staging/src/client/main.py"
